# Generated by Django 3.1.7 on 2021-05-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemonapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPokemon', models.IntegerField(default=0, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('hp', models.IntegerField(default=0)),
                ('attack', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('specialAttack', models.IntegerField(default=0)),
                ('specialDefense', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('peso', models.CharField(max_length=10)),
                ('altura', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
    ]
