# Generated by Django 3.1.7 on 2021-05-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonapp',
            name='imagensprite',
            field=models.TextField(blank=True, default='0', null=True),
        ),
    ]
